#PlaceholderAPI configuration file
version: 2

#Sets the minimal delay between separate updates of a placeholder (in ticks).
min_update_interval: 10

#Sets the minimal delay between separate updates of an async placeholder (in ticks). Async placeholders usually processes some expansive operations and shouldn't be processed too often
min_async_update_interval: 200

#format for date placeholder
date_format: "yyyy-MM-dd"

#format for time placeholder
time_format: "HH:mm:ss"

boolean_format:
  true: "yes"
  false: "no"

#number of digits displayed
coordinates_accuracy: 2