#PlaceholderAPI configuration file
version: 2

#Sets the minimal delay between separate updates of a placeholder (in ticks).
min_update_interval: 10

#Sets the minimal delay between separate updates of an async placeholder (in ticks). Async placeholders usually processes some expensive operations and shouldn't be processed too often
min_async_update_interval: 200

#format for date placeholder
date_format: "yyyy-MM-dd"

#format for time placeholder
time_format: "HH:mm:ss"

boolean_format:
  true_format: "yes"
  false_format: "no"

#separator to format arrays. So list of players will be formatted like "player1, player2, player3"
array_format: ", "

#number of digits displayed
coordinates_accuracy: 2