name: PlaceholderAPI
version: "2.2"
main: com.creeperface.nukkit.placeholderapi.PlaceholderPlugin
api: ["1.0.0"]
description: API which provides placeholder managment with easy usage
author: CreeperFace
depend: [ "KotlinLib" ]