name: PlaceholderAPI
version: 1.3
main: com.creeperface.nukkit.placeholderapi.PlaceholderPlugin
api: ["1.0.0"]
description: API which provides placeholder managment with easy usage
author: CreeperFace